# Generated by Django 2.2.6 on 2020-08-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_makeup_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wedding/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото свадебного образа',
                'verbose_name_plural': 'Фотки свадебных образов',
            },
        ),
    ]
