# Generated by Django 2.0 on 2020-08-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200809_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hair_img',
            name='image',
            field=models.ImageField(upload_to='hair/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='makeup_img',
            name='image',
            field=models.ImageField(upload_to='makeup/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='wedding_img',
            name='image',
            field=models.ImageField(upload_to='wedding/', verbose_name='Фото'),
        ),
    ]
